// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF6cQPEUrcm8YeoE9vVxy4EeVb7X7R6dA',
    appId: '1:614646586020:web:8e0c33d6009d126052a431',
    messagingSenderId: '614646586020',
    projectId: 'rent-car-a80a4',
    authDomain: 'rent-car-a80a4.firebaseapp.com',
    storageBucket: 'rent-car-a80a4.appspot.com',
    measurementId: 'G-JX7G9F5FE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbPMVd4fRVHYKWOKI2CMmggtmBUDf7T0A',
    appId: '1:614646586020:android:e47eff57922b6e9f52a431',
    messagingSenderId: '614646586020',
    projectId: 'rent-car-a80a4',
    storageBucket: 'rent-car-a80a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn0jVKs9muA3I8U_ecyw6jUGZ-k5Z0HaI',
    appId: '1:614646586020:ios:da9a8db6d0e5036152a431',
    messagingSenderId: '614646586020',
    projectId: 'rent-car-a80a4',
    storageBucket: 'rent-car-a80a4.appspot.com',
    iosBundleId: 'com.example.rentCar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn0jVKs9muA3I8U_ecyw6jUGZ-k5Z0HaI',
    appId: '1:614646586020:ios:da9a8db6d0e5036152a431',
    messagingSenderId: '614646586020',
    projectId: 'rent-car-a80a4',
    storageBucket: 'rent-car-a80a4.appspot.com',
    iosBundleId: 'com.example.rentCar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF6cQPEUrcm8YeoE9vVxy4EeVb7X7R6dA',
    appId: '1:614646586020:web:72b7d7bf2c9a779d52a431',
    messagingSenderId: '614646586020',
    projectId: 'rent-car-a80a4',
    authDomain: 'rent-car-a80a4.firebaseapp.com',
    storageBucket: 'rent-car-a80a4.appspot.com',
    measurementId: 'G-B46M6DP8M1',
  );

}